In [6]:
import requests
import json

url="https://raw.githubusercontent.com/IBM/taxinomitis/master/resources/datasets/numbers/titanic.json"
reponse = requests.get(url).text
# print(data, type(data))  # str

data = json.loads(reponse) 
# print(data["metadata"])

fields = []
for tmp in data["metadata"]["fields"]:
    fields.append(tmp['name'].replace(".",""))

fields.append('servived')
print(fields)

arr = []
for tmp in data["data"]["survived"]:
    tmp1 = { fields[0]:int(tmp[0]), 
             fields[1]:tmp[1],
             fields[2]:float(tmp[2]),
             fields[3]:int(tmp[3]),
             fields[4]:int(tmp[4]),
             fields[5]:float(tmp[5]),
             fields[6]:tmp[6],
             fields[7]:1 }
    arr.append(tmp1)

    
for tmp in data["data"]["did_not_survive"]:
    tmp1 = { fields[0]:int(tmp[0]), 
             fields[1]:tmp[1],
             fields[2]:float(tmp[2]),
             fields[3]:int(tmp[3]),
             fields[4]:int(tmp[4]),
             fields[5]:float(tmp[5]),
             fields[6]:tmp[6],
             fields[7]:0 }
    arr.append(tmp1)
arr

['ticket class', 'gender', 'age', 'sibl sp', 'par ch', 'ticket fare', 'embarked', 'servived']

[{'ticket class': 3,
  'gender': 'male',
  'age': 0.42,
  'sibl sp': 0,
  'par ch': 1,
  'ticket fare': 8.5167,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'female',
  'age': 0.75,
  'sibl sp': 2,
  'par ch': 1,
  'ticket fare': 19.2583,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'female',
  'age': 0.75,
  'sibl sp': 2,
  'par ch': 1,
  'ticket fare': 19.2583,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'female',
  'age': 1.0,
  'sibl sp': 0,
  'par ch': 2,
  'ticket fare': 15.7417,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'male',
  'age': 1.0,
  'sibl sp': 0,
  'par ch': 2,
  'ticket fare': 37.0042,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'female',
  'age': 3.0,
  'sibl sp': 1,
  'par ch': 2,
  'ticket fare': 41.5792,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'female',
  'age': 4.0,
  'sibl sp': 0,
  'par ch': 1,
  'ticket fare': 13.4167,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'female',
  'age': 5.0,
  'sibl sp': 2,
  'par ch': 1,
  'ticket fare': 19.2583,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'male',
  'age': 12.0,
  'sibl sp': 1,
  'par ch': 0,
  'ticket fare': 11.2417,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'female',
  'age': 13.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 7.2292,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'female',
  'age': 14.0,
  'sibl sp': 1,
  'par ch': 0,
  'ticket fare': 30.0708,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'female',
  'age': 14.0,
  'sibl sp': 1,
  'par ch': 0,
  'ticket fare': 11.2417,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'female',
  'age': 15.0,
  'sibl sp': 1,
  'par ch': 0,
  'ticket fare': 14.4542,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'female',
  'age': 15.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 7.225,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 16.0,
  'sibl sp': 0,
  'par ch': 1,
  'ticket fare': 57.9792,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 17.0,
  'sibl sp': 1,
  'par ch': 0,
  'ticket fare': 108.9,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'female',
  'age': 17.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 12.0,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'male',
  'age': 17.0,
  'sibl sp': 0,
  'par ch': 2,
  'ticket fare': 110.8833,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 18.0,
  'sibl sp': 2,
  'par ch': 2,
  'ticket fare': 262.375,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 18.0,
  'sibl sp': 1,
  'par ch': 0,
  'ticket fare': 227.525,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 19.0,
  'sibl sp': 1,
  'par ch': 0,
  'ticket fare': 91.0792,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'male',
  'age': 20.0,
  'sibl sp': 1,
  'par ch': 1,
  'ticket fare': 15.7417,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'male',
  'age': 20.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 7.2292,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 21.0,
  'sibl sp': 2,
  'par ch': 2,
  'ticket fare': 262.375,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 22.0,
  'sibl sp': 0,
  'par ch': 2,
  'ticket fare': 49.5,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'male',
  'age': 22.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 7.225,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'female',
  'age': 22.0,
  'sibl sp': 1,
  'par ch': 2,
  'ticket fare': 41.5792,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'male',
  'age': 23.0,
  'sibl sp': 0,
  'par ch': 1,
  'ticket fare': 63.3583,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 23.0,
  'sibl sp': 1,
  'par ch': 0,
  'ticket fare': 113.275,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'female',
  'age': 23.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 13.7917,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 24.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 83.1583,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 24.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 69.3,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 24.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 69.3,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 24.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 49.5042,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'female',
  'age': 24.0,
  'sibl sp': 0,
  'par ch': 3,
  'ticket fare': 19.2583,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'male',
  'age': 25.0,
  'sibl sp': 1,
  'par ch': 0,
  'ticket fare': 55.4417,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'male',
  'age': 25.0,
  'sibl sp': 1,
  'par ch': 0,
  'ticket fare': 91.0792,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'male',
  'age': 26.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 18.7875,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'male',
  'age': 26.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 30.0,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'male',
  'age': 27.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 76.7292,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'female',
  'age': 27.0,
  'sibl sp': 1,
  'par ch': 0,
  'ticket fare': 13.8583,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'female',
  'age': 28.0,
  'sibl sp': 1,
  'par ch': 0,
  'ticket fare': 24.0,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'female',
  'age': 29.0,
  'sibl sp': 0,
  'par ch': 2,
  'ticket fare': 15.2458,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'male',
  'age': 29.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 7.8958,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 30.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 56.9292,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 30.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 106.425,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 30.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 31.0,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 31.0,
  'sibl sp': 1,
  'par ch': 0,
  'ticket fare': 113.275,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 32.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 76.2917,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'male',
  'age': 32.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 30.5,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 35.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 512.3292,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'male',
  'age': 35.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 26.55,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'male',
  'age': 35.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 512.3292,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 36.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 135.6333,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'male',
  'age': 36.0,
  'sibl sp': 0,
  'par ch': 1,
  'ticket fare': 512.3292,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 38.0,
  'sibl sp': 1,
  'par ch': 0,
  'ticket fare': 71.2833,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 38.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 227.525,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 39.0,
  'sibl sp': 1,
  'par ch': 1,
  'ticket fare': 110.8833,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 39.0,
  'sibl sp': 1,
  'par ch': 1,
  'ticket fare': 83.1583,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'male',
  'age': 40.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 31.0,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 40.0,
  'sibl sp': 1,
  'par ch': 1,
  'ticket fare': 134.5,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 41.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 134.5,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 42.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 227.525,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 44.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 27.7208,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 44.0,
  'sibl sp': 0,
  'par ch': 1,
  'ticket fare': 57.9792,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 48.0,
  'sibl sp': 1,
  'par ch': 0,
  'ticket fare': 39.6,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'male',
  'age': 48.0,
  'sibl sp': 1,
  'par ch': 0,
  'ticket fare': 76.7292,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 49.0,
  'sibl sp': 1,
  'par ch': 0,
  'ticket fare': 76.7292,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'male',
  'age': 49.0,
  'sibl sp': 1,
  'par ch': 0,
  'ticket fare': 89.1042,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'male',
  'age': 49.0,
  'sibl sp': 1,
  'par ch': 0,
  'ticket fare': 56.9292,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 50.0,
  'sibl sp': 0,
  'par ch': 1,
  'ticket fare': 247.5208,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 52.0,
  'sibl sp': 1,
  'par ch': 0,
  'ticket fare': 78.2667,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 54.0,
  'sibl sp': 1,
  'par ch': 0,
  'ticket fare': 78.2667,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 54.0,
  'sibl sp': 1,
  'par ch': 0,
  'ticket fare': 59.4,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'male',
  'age': 56.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 35.5,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 56.0,
  'sibl sp': 0,
  'par ch': 1,
  'ticket fare': 83.1583,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 58.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 146.5208,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 60.0,
  'sibl sp': 1,
  'par ch': 0,
  'ticket fare': 75.25,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'male',
  'age': 60.0,
  'sibl sp': 1,
  'par ch': 1,
  'ticket fare': 79.2,
  'embarked': 'Cherbourg',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'female',
  'age': 15.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 8.0292,
  'embarked': 'Queenstwn',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'female',
  'age': 16.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 7.7333,
  'embarked': 'Queenstwn',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'female',
  'age': 16.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 7.75,
  'embarked': 'Queenstwn',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'female',
  'age': 19.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 7.8792,
  'embarked': 'Queenstwn',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'female',
  'age': 22.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 7.75,
  'embarked': 'Queenstwn',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'male',
  'age': 29.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 7.75,
  'embarked': 'Queenstwn',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'female',
  'age': 30.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 12.35,
  'embarked': 'Queenstwn',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 33.0,
  'sibl sp': 1,
  'par ch': 0,
  'ticket fare': 90.0,
  'embarked': 'Queenstwn',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'male',
  'age': 0.67,
  'sibl sp': 1,
  'par ch': 1,
  'ticket fare': 14.5,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'male',
  'age': 0.83,
  'sibl sp': 0,
  'par ch': 2,
  'ticket fare': 29.0,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'male',
  'age': 0.83,
  'sibl sp': 1,
  'par ch': 1,
  'ticket fare': 18.75,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'male',
  'age': 0.92,
  'sibl sp': 1,
  'par ch': 2,
  'ticket fare': 151.55,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'female',
  'age': 1.0,
  'sibl sp': 1,
  'par ch': 1,
  'ticket fare': 11.1333,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'male',
  'age': 1.0,
  'sibl sp': 2,
  'par ch': 1,
  'ticket fare': 39.0,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'male',
  'age': 1.0,
  'sibl sp': 1,
  'par ch': 2,
  'ticket fare': 20.575,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'male',
  'age': 2.0,
  'sibl sp': 1,
  'par ch': 1,
  'ticket fare': 26.0,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'female',
  'age': 2.0,
  'sibl sp': 0,
  'par ch': 1,
  'ticket fare': 12.2875,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'female',
  'age': 2.0,
  'sibl sp': 1,
  'par ch': 1,
  'ticket fare': 26.0,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'male',
  'age': 3.0,
  'sibl sp': 1,
  'par ch': 1,
  'ticket fare': 26.0,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'male',
  'age': 3.0,
  'sibl sp': 4,
  'par ch': 2,
  'ticket fare': 31.3875,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'male',
  'age': 3.0,
  'sibl sp': 1,
  'par ch': 1,
  'ticket fare': 15.9,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'male',
  'age': 3.0,
  'sibl sp': 1,
  'par ch': 1,
  'ticket fare': 18.75,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'female',
  'age': 4.0,
  'sibl sp': 1,
  'par ch': 1,
  'ticket fare': 16.7,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'female',
  'age': 4.0,
  'sibl sp': 0,
  'par ch': 2,
  'ticket fare': 22.025,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'male',
  'age': 4.0,
  'sibl sp': 0,
  'par ch': 2,
  'ticket fare': 81.8583,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'female',
  'age': 4.0,
  'sibl sp': 2,
  'par ch': 1,
  'ticket fare': 39.0,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'female',
  'age': 4.0,
  'sibl sp': 1,
  'par ch': 1,
  'ticket fare': 23.0,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'male',
  'age': 4.0,
  'sibl sp': 1,
  'par ch': 1,
  'ticket fare': 11.1333,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'female',
  'age': 5.0,
  'sibl sp': 1,
  'par ch': 2,
  'ticket fare': 27.75,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'female',
  'age': 5.0,
  'sibl sp': 4,
  'par ch': 2,
  'ticket fare': 31.3875,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'female',
  'age': 5.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 12.475,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'female',
  'age': 6.0,
  'sibl sp': 0,
  'par ch': 1,
  'ticket fare': 33.0,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'male',
  'age': 6.0,
  'sibl sp': 0,
  'par ch': 1,
  'ticket fare': 12.475,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'female',
  'age': 7.0,
  'sibl sp': 0,
  'par ch': 2,
  'ticket fare': 26.25,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'female',
  'age': 8.0,
  'sibl sp': 0,
  'par ch': 2,
  'ticket fare': 26.25,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'male',
  'age': 8.0,
  'sibl sp': 1,
  'par ch': 1,
  'ticket fare': 36.75,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'male',
  'age': 9.0,
  'sibl sp': 0,
  'par ch': 2,
  'ticket fare': 20.525,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'male',
  'age': 9.0,
  'sibl sp': 1,
  'par ch': 1,
  'ticket fare': 15.9,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'male',
  'age': 11.0,
  'sibl sp': 1,
  'par ch': 2,
  'ticket fare': 120.0,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'female',
  'age': 13.0,
  'sibl sp': 0,
  'par ch': 1,
  'ticket fare': 19.5,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 14.0,
  'sibl sp': 1,
  'par ch': 2,
  'ticket fare': 120.0,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 15.0,
  'sibl sp': 0,
  'par ch': 1,
  'ticket fare': 211.3375,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'male',
  'age': 16.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 8.05,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 16.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 86.5,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 16.0,
  'sibl sp': 0,
  'par ch': 1,
  'ticket fare': 39.4,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 3,
  'gender': 'female',
  'age': 17.0,
  'sibl sp': 4,
  'par ch': 2,
  'ticket fare': 7.925,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 2,
  'gender': 'female',
  'age': 17.0,
  'sibl sp': 0,
  'par ch': 0,
  'ticket fare': 10.5,
  'embarked': 'Southampt',
  'servived': 1},
 {'ticket class': 1,
  'gender': 'female',
  'age': 17.0,
  'sibl sp': 1,
  'par ch': 0,

In [9]:
# csv파일 만들어 데이터 저장
import csv


# 저장위치 ,w ,r ,a ,utf-8 ,euc-kr
file = open('csv/titanic.csv','w',encoding='utf-8')
wr = csv.writer(file) 
wr.writerow(['ticket class','gender','age','sibl sp','par ch','ticket fare','embarked','servived']) # column명 추가
for i in arr:
    wr.writerow(i)
file.close()

TypeError: the JSON object must be str, bytes or bytearray, not list